name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  IMAGE: ghcr.io/becojo/math-homeworks:latest

jobs:
  build:
    permissions:
      packages: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build image
      run: docker build . --file Dockerfile --tag "$IMAGE"
      
    - name: Push image
      run: docker push "$IMAGE"

    - uses: sigstore/cosign-installer@main

    - name: Sign the images
      run: |
        cosign sign "$IMAGE"

    - name: Verify the pushed tags
      run: |
        cosign verify "$IMAGE"

